# DO NOT EDIT THIS FILE --- This file is a managed file, do not edit it directly.
#
# ===========================================================================
# LOCAL MODIFICATIONS -- READ THIS BEFORE REGENERATING
#
# The banner above is not true any more: this file HAS been hand-edited. It is
# regenerated by the STM32Cube VS Code extension (project refresh, .ioc sync,
# toolchain change), and a regeneration will silently overwrite the change
# listed below. After any regeneration, re-apply it or the build breaks.
#
#  1) -fcyclomatic-complexity removed
#     Where:    target_compile_options(), C and CXX, Debug and Release -- four
#               occurrences in the generated file.
#     Why:      it is an STMicroelectronics extension, present only in the GCC
#               bundled with STM32CubeIDE. This project builds with the stock
#               Arm GNU Toolchain (14.3.rel1), which rejects it outright:
#               "error: unrecognized command-line option". The flag only fed
#               CubeIDE's complexity-analysis view; it does not affect code
#               generation, so removing it does not change the output binary.
#
# Note: unlike the application's cmake/flags.cmake, this file does NOT carry
# the LINKER_SCRIPT variable substitution. The bootloader is built from a
# single linker script (STM32F401RETX_FLASH.ld, hardcoded in the Debug and
# Release target_link_options() blocks below) because it is not slot-relocated
# -- it always lives at the flash base. Do not "fix" that for symmetry with
# the app.
# ===========================================================================

set_target_properties(${PROJECT_NAME} PROPERTIES SUFFIX ".elf")

target_compile_options(${PROJECT_NAME} PUBLIC
    ${CPU_FLAGS}
    ${CC_SECURE}
    # Compiler flags specific to Debug build type
    $<$<CONFIG:Debug>:
      $<$<COMPILE_LANGUAGE:C>: 
        --specs=nano.specs
        -std=gnu11
        -g3
        -O0
        -Wall
        -fstack-usage
      >
      $<$<COMPILE_LANGUAGE:CXX>: 
        --specs=nano.specs
        -std=gnu++14
        -g3
        -O0
        -fno-use-cxa-atexit
        -Wall
        -fstack-usage
      >

      $<$<COMPILE_LANGUAGE:ASM>: 
        --specs=nano.specs
        -g3
        -x
        assembler-with-cpp
      >
    >

    # Compiler flags specific to Release build type
    $<$<CONFIG:Release>:
      $<$<COMPILE_LANGUAGE:C>: 
        --specs=nano.specs
        -std=gnu11
        -Os
        -Wall
        -fstack-usage
      >
      $<$<COMPILE_LANGUAGE:CXX>: 
        --specs=nano.specs
        -std=gnu++14
        -Os
        -fno-use-cxa-atexit
        -Wall
        -fstack-usage
      >

      $<$<COMPILE_LANGUAGE:ASM>: 
        --specs=nano.specs
        -x
        assembler-with-cpp
      >
    >

)

target_include_directories(${PROJECT_NAME} PUBLIC 
    "${CMAKE_CURRENT_SOURCE_DIR}/Core/Inc"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F4xx_HAL_Driver/Inc"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/CMSIS/Device/ST/STM32F4xx/Include"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/CMSIS/Include"
)

target_compile_definitions(${PROJECT_NAME} PUBLIC 
    # Symbols specific to Debug build type
    $<$<CONFIG:Debug>: 
      $<$<COMPILE_LANGUAGE:C>: 
        DEBUG
        USE_HAL_DRIVER
        STM32F401xE
      >
    
      $<$<COMPILE_LANGUAGE:ASM>: 
        DEBUG
      >
    >

    
    # Symbols specific to Release build type
    $<$<CONFIG:Release>: 
      $<$<COMPILE_LANGUAGE:C>: 
        USE_HAL_DRIVER
        STM32F401xE
      >
    >

    
)

target_link_options(${PROJECT_NAME} PUBLIC 
    ${CPU_FLAGS}
    ${CC_SECURE}

    # Linker flags specific to Debug build type
    $<$<CONFIG:Debug>: 
        --specs=nano.specs
        -T${CMAKE_CURRENT_BINARY_DIR}/STM32F401RETX_FLASH.ld
        --specs=nosys.specs
        -Wl,-Map=${CMAKE_CURRENT_BINARY_DIR}/b2_bootloader.map
        -static
    >

    # Linker flags specific to Release build type
    $<$<CONFIG:Release>: 
        --specs=nano.specs
        -T${CMAKE_CURRENT_BINARY_DIR}/STM32F401RETX_FLASH.ld
        --specs=nosys.specs
        -Wl,-Map=${CMAKE_CURRENT_BINARY_DIR}/b2_bootloader.map
        -static
    >

)
# Clean .map file
set_property(DIRECTORY APPEND PROPERTY ADDITIONAL_CLEAN_FILES "${CMAKE_SOURCE_DIR}/build/${CMAKE_BUILD_TYPE}/${PROJECT_NAME}.map")
